import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Info"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"

[font.bold]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"
style = "Medium Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
opacity = 1.0
startup_mode = "Fullscreen"
