import = [
  # "~/.config/alacritty/themes/themes/ashes_dark.toml"
  # "~/.config/alacritty/themes/themes/ashes_light.toml"
  # "~/.config/alacritty/themes/themes/atom_one_light.toml"
  # "~/.config/alacritty/themes/themes/ayu_dark.toml"
  # "~/.config/alacritty/themes/themes/ayu_light.toml"
  # "~/.config/alacritty/themes/themes/base16_default_dark.toml"
  # "~/.config/alacritty/themes/themes/carbonfox.toml"
  # "~/.config/alacritty/themes/themes/catppuccin.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
  # "~/.config/alacritty/themes/themes/darcula.toml"
  # "~/.config/alacritty/themes/themes/dark_pastels.toml"
  # "~/.config/alacritty/themes/themes/doom_one.toml"
  # "~/.config/alacritty/themes/themes/dracula.toml"
  # "~/.config/alacritty/themes/themes/everforest_dark.toml"
  # "~/.config/alacritty/themes/themes/everforest_light.toml"
  # "~/.config/alacritty/themes/themes/falcon.toml"
  # "~/.config/alacritty/themes/themes/github_dark.toml"
  # "~/.config/alacritty/themes/themes/github_dark_colorblind.toml"
  # "~/.config/alacritty/themes/themes/github_dark_default.toml"
  # "~/.config/alacritty/themes/themes/github_dark_dimmed.toml"
  # "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
  # "~/.config/alacritty/themes/themes/github_dark_tritanopia.toml"
  # "~/.config/alacritty/themes/themes/github_light.toml"
  # "~/.config/alacritty/themes/themes/github_light_colorblind.toml"
  # "~/.config/alacritty/themes/themes/github_light_default.toml"
  # "~/.config/alacritty/themes/themes/github_light_high_contrast.toml"
  # "~/.config/alacritty/themes/themes/github_light_tritanopia.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_light.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_material.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_material_medium_light.toml"
  # "~/.config/alacritty/themes/themes/horizon-dark.toml"
  # "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
  # "~/.config/alacritty/themes/themes/monokai_pro.toml"
  # "~/.config/alacritty/themes/themes/nightfox.toml"
  # "~/.config/alacritty/themes/themes/nord.toml"
  # "~/.config/alacritty/themes/themes/nord_light.toml"
  # "~/.config/alacritty/themes/themes/oceanic_next.toml"
  # "~/.config/alacritty/themes/themes/onedark.toml"
  # "~/.config/alacritty/themes/themes/palenight.toml"
  # "~/.config/alacritty/themes/themes/solarized_dark.toml"
  # "~/.config/alacritty/themes/themes/solarized_light.toml"
  # "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
  # "~/.config/alacritty/themes/themes/tokyo-night.toml"
  # "~/.config/alacritty/themes/themes/tomorrow_night.toml"
  # "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"
  # "~/.config/alacritty/themes/themes/ubuntu.toml"
  # "~/.config/alacritty/themes/themes/wombat.toml"
]

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Info"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"

[font.bold]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"
style = "Medium Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
opacity = 1.0
startup_mode = "Fullscreen"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" }
]
