# Inserts a blank line between shell prompts
add_newline = false

# Which is equivalent to
format="""
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character"""
right_format = """
$kubernetes\
$c\
$cmake\
$golang\
$haskell\
$java\
$lua\
$nodejs\
$python\
$rust\
$zig\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell"""

# Symbols
[aws]
symbol = "  "
disabled = true

[c]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[kubernetes]
format = 'on [$symbol$context( \($namespace\))]($style) '
disabled = false
detect_files = ["main.tf"]
detect_folders = [".kube"]

[lua]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "
style = "green bold"

[rust]
symbol = " "

[zig]
symbol = " "

[gcloud]
disabled = true
