#!/usr/bin/env bash
# Returns the current playing song in Spotify for OSX

sleep 3  # Wait to let spotify remain closed after closing

if [ $(osascript -e 'application "Spotify" is running') = "true" ]; then

  state=`osascript -e 'tell application "Spotify" to player state as string'`;
  artist=`osascript -e 'tell application "Spotify" to artist of current track as string'`;
  track=`osascript -e 'tell application "Spotify" to name of current track as string'`;

  if [ $state = "playing" ]; then
    echo '#[fg=#1db954,bg=default,bold,blink] ♫ '$artist - $track' '
  elif [ $state = "paused" ]; then
    echo '#[fg=#1db954,bg=default,bold] ❚❚ '$artist - $track' '
  else
    echo ''
  fi
else
  echo ''
fi
